[package]
name = "liyu-server"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.3", features = ["postgres", "r2d2", "serde_json"] }
diesel_migrations = "2.3"
salvo = { version = "0.84", features = ["http1", "server"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
