DROP INDEX gifts_outbox_idx;
DROP INDEX gifts_inbox_idx;
ALTER TABLE gifts
    DROP CONSTRAINT gifts_state_check,
    DROP COLUMN voucher_code,
    DROP COLUMN settled_at,
    DROP COLUMN revealed_at,
    DROP COLUMN opened_at,
    DROP COLUMN expires_at,
    DROP COLUMN available_at,
    DROP COLUMN identity_known,
    DROP COLUMN attempts,
    DROP COLUMN contract_text,
    DROP COLUMN message,
    DROP COLUMN answer_hash,
    DROP COLUMN clue,
    DROP COLUMN unlock_kind,
    DROP COLUMN price_cents;
